### ISSUE TITLE
Fatal error caused by na NULL value

### ISSUE THREAD

**Issue by Every0ne** [marcantondahmen/automad#47]
After update to 1.10.8 my instance is throwing
```
Fatal error: Uncaught TypeError: Automad\UI\InPage::injectTemporaryEditButton(): Argument #1 ($value) must be of type string, null given, called in /automad/src/Engine/Processors/ContentProcessor.php on line 269 and defined in /automad/src/UI/InPage.php:95 Stack trace: #0 /automad/src/Engine/Processors/ContentProcessor.php(269): Automad\UI\InPage->injectTemporaryEditButton() #1 [internal function]: Automad\Engine\Processors\ContentProcessor->Automad\Engine\Processors\{closure}() #2 /automad/src/Engine/Processors/ContentProcessor.php(200): preg_replace_callback() #3 /automad/src/Engine/Processors/TemplateProcessor.php(105): Automad\Engine\Processors\ContentProcessor->processVariables() #4 [internal function]: Automad\Engine\Processors\TemplateProcessor->Automad\Engine\Processors\{closure}() #5 /automad/src/Engine/Processors/TemplateProcessor.php(102): preg_replace_callback() #6 /automad/src/Engine/Processors/ContentProcessor.php(156): Automad\Engine\Processors\TemplateProcessor->process() #7 /automad/src/Engine/Processors/Features/ContextProcessor.php(124): Automad\Engine\Processors\ContentProcessor->processFileSnippet() #8 /automad/src/Engine/Processors/TemplateProcessor.php(109): Automad\Engine\Processors\Features\ContextProcessor->process() #9 [internal function]: Automad\Engine\Processors\TemplateProcessor->Automad\Engine\Processors\{closure}() #10 /automad/src/Engine/Processors/TemplateProcessor.php(102): preg_replace_callback() #11 /automad/src/Engine/Processors/Features/IncludeProcessor.php(69): Automad\Engine\Processors\TemplateProcessor->process() #12 /automad/src/Engine/Processors/TemplateProcessor.php(109): Automad\Engine\Processors\Features\IncludeProcessor->process() #13 [internal function]: Automad\Engine\Processors\TemplateProcessor->Automad\Engine\Processors\{closure}() #14 /automad/src/Engine/Processors/TemplateProcessor.php(102): preg_replace_callback() #15 /automad/src/Engine/View.php(125): Automad\Engine\Processors\TemplateProcessor->process() #16 /automad/src/App.php(167): Automad\Engine\View->render() #17 /automad/src/App.php(180): Automad\App->Automad\{closure}() #18 /automad/src/App.php(91): Automad\App->render() #19 /automad/init.php(40): Automad\App->__construct() #20 /index.php(4): require('...') #21 {main} thrown in /automad/src/UI/InPage.php on line 95
```
Apparently `$value` in _ContentProcessor_ method _processVariables_ becomes NULL sometimes and it causes problems down the stream. At this point I can't tell why the value becomes NULL, so for now I just monkeypatched it to become an empty string if it's NULL, just before the call to _injectTemporaryEditButton()_ is made.

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting. Do you use any extension that may return NULL in some cases?

**Comment by marcantondahmen** [comment]
I just released a patch that handles type errors caused by extensions that may return null instead of a string.

**Comment by Every0ne** [comment]
Yes, it's entirely possible that some of my extensions were returning NULL in some circumstances. Thank you for patching that in 1.10.9.
